name: citadel
description: "A fully open source, demonstrably fast, and verifiably free forever messenger."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Use a more recent SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # For P2P networking, using the best available libp2p implementation [F1]
  dart_libp2p: ^0.1.2 # <-- CORRECTED to the right package name and a recent version

  # For secure on-device storage of the mnemonic phrase [F4]
  flutter_secure_storage: ^9.0.0
  
  # For the encrypted local database [F4]
  sqflite_sqlcipher: ^2.2.1
  path_provider: ^2.1.1 
  path: ^1.8.3

  # For Identity & Cryptography [F2], [F3], [ID3]
  bip39: ^1.0.6
  pinenacl: ^0.5.0
  
  # UI & Utility
  cupertino_icons: ^1.0.8
  
  # A simple service locator for dependency injection to keep our code clean
  get_it: ^7.6.7
  
  # For state management to update the UI efficiently
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
