name: citadel
description: An offline, mesh-based, voice-only empathy thread app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Functionality
  # ------------------
  # Mesh Networking: Wraps Nordic's nRF Mesh SDKs for iOS and Android.
  nordic_nrf_mesh: ^0.13.0

  # BLE Scanning & Connectivity: Required by the mesh plugin.
  flutter_reactive_ble: ^5.2.0

  # Audio Recording & Playback
  flutter_sound: ^9.2.13

  # Local Storage: A lightweight and fast key-value database.
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # File System Paths: To find a safe location for the Hive database.
  path_provider: ^2.0.15

  # Cryptography: For end-to-end encryption of voice notes.
  encrypt: ^5.0.1

  # State Management: For managing UI state reactively and efficiently.
  # Using Riverpod for its compile-safety and scalability.
  flutter_riverpod: ^2.3.6

  # Permissions Handling: To request necessary permissions like Bluetooth and Location.
  permission_handler: ^10.4.3

  # Geo-coordinates & Mapping
  # For mocking geo-data and displaying on the map.
  google_maps_flutter: ^2.4.0
  geolocator: ^10.0.0 # To get mock or real location data.

  # UI & UX
  # ---------
  # Icons: A comprehensive icon pack.
  cupertino_icons: ^1.0.2

  # UUID Generation: For creating unique IDs for voice pins and threads.
  uuid: ^3.0.7

  # Formatting Timestamps: For human-readable time displays.
  intl: ^0.18.1

  # For generating waveform data from audio files.
  audio_waveforms: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation: Required by Hive to generate TypeAdapter classes.
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
